[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type= ["lib"]

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
sea-orm = { version = "1.1.10", features = [ "sqlx-sqlite", "runtime-async-std-native-tls", "macros" ] }