//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::quote::Entity as Quote;
pub use super::quote_tag_association::Entity as QuoteTagAssociation;
pub use super::tag::Entity as Tag;
